svc_switch:
  ip: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
  namespace: test111

monitor_check:
    ip: 127.0.0.1
    port: 9999
    username: TnwiYL3kXmW5Fg5WVj/GkTK8+QIeh7wtCORJsZl6b1JR1QCmG08+nZ9Z1qfG88KitWFGESPrFidbYfC1QxHa8zvXY5ivGsMi6qqcaaOeEY50z9ub5VYnI4uI4hLogq+/NgUnlKLy2ba0OJSMTFIl6xBPPLn714mTfQfzW8JMEtA=
    password: b5b/zFNDrIVklXG455w9PtHvdhI3/i2K3UDuu3I793oBfJgC/L5Ybv1Cxu84WwWNWZ0+QG7O/9tBVzZBhBnMjhbUGLgPgR5mLjFRQF3QdZ42E3+PGTPwO1LZ2Z1qY54oouRk66rXaBIOFJ3d+VvwbLHF75o9xbBBxjbAzOC+1iQ=
    version: 1

db_tool:
  gscf:
    ip: 127.0.0.1
    port: 5432
    username: postgres
    password: postgre
    dbname: postgres
    searchPath: public
  cpyy:
    ip: 127.0.0.1
    port: 5432
    username: postgres
    password: postgress
    dbname: postgres
    searchPath: public

web_server:
  port: 17000

log:
  filename: ./logs/all.log
  level: info
  out_type: 3

jasypt:
  salt: 123456
redis_tool:
    mode: sentinel
    addr: 192.168.56.128:27001,192.168.56.128:27002,192.168.56.128:27003
    password: ENC(K6FNl1c/9aOW1RNhnxGNRI+usHFynK/m)
    sentinelPassword: ENC(K6FNl1c/9aOW1RNhnxGNRI+usHFynK/m)
    masterName: mymaster
    db: 1
