web:
  server:
    port: 18080

nacos:
  server:
    ip: 127.0.0.1
    port: 8848
    username: nacos
    password: nacos
    namespace: cdl

monitor:
  server:
    ip: 127.0.0.1
    port: 9999
    username: sysadmin
    password: Grcf#jk9527

sql:
  server:
    ip: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    dbname: postgres
    searchPath: public

web_server:
  port: 17000

log:
  filename: ./logs/all.log
  level: info
  out_type: 2

jasypt:
  salt: 123456