svc_switch.:
  ip: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
  namespace: test111

monitor_server:
  cfzt:
    aaabbc:
      ip: 127.0.0.1
      port: 9999
      username: sysadmin
      password: Grcf#jk9527

db_tool:
  cfzt:
    ip: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    dbname: postgres
    searchPath: public
  gscf:
    ip: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    dbname: postgres
    searchPath: public

web_server:
  port: 17000

log:
  filename: ./logs/all.log
  level: info
  out_type: 2

jasypt:
  salt: 123456
redis:
  server:
    - sourceName: a
      ip: 192.168.56.128
      port: 17001
      password: ENC(K6FNl1c/9aOW1RNhnxGNRI+usHFynK/m)

redis_tool :
